### ISSUE TITLE
unifi_ssl_import.sh: "unable to import the certificate into keystore"

### ISSUE THREAD

**Issue by katzrkool** [stevejenkins/unifi-linux-utils#27]
When running `unifi_ssl_import.sh`, it runs through everything fine, until it tries to import the cert authority into the keystore. 

```
Importing SSL certificate into UniFi keystore...

Importing certificate authority into UniFi keystore...

Unable to import the certificate into keystore

Removing temporary files...

Restarting UniFi Controller to apply new Let's Encrypt SSL certificate...

Done!
```

Even though it says it's  done, the controller is inaccessable. 

I'm running Unifi Controller 5.9.29 on Raspbian 9.4

Any help would be greatly appreciated, thanks!

**Comment by est-it** [comment]
I've the same problem on the same version.

**Comment by katzrkool** [comment]
@est-it Thank you so much! It worked!
